name: Build & Deploy Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mcyt-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: benhall1998/mcytbot
          TAG_NAME: "latest"
      
      - name: Send Restart Request
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@8e939c608aea2d5df19da3e8229cf035f7aa9e4c
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          # Request URL
          url: ${{ secrets.PANEL_URL }}
          # Request Method
          method: POST
          # Content Type
          contentType: application/json
          # Request Body as JSON String
          data: '{"signal": "restart"}'
          # Bearer Authentication Token
          bearerToken: ${{ secrets.PANEL_API_KEY }}
      - name: Webhook Notification
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
